pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '.'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'PropertyChangedAnalyzers.Test'
    arguments: '--no-build --configuration=$(buildConfiguration)'